version 2.0

diff --git a/.github/workflows/on-release-publish.yml b/.github/workflows/on-release-publish.yml
--- a/.github/workflows/on-release-publish.yml
+++ b/.github/workflows/on-release-publish.yml
@@ -9,6 +9,46 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+
+    - name: define settings modifier function
+      run: |
+        update_release_settings() {
+          case "$1" in
+            "early")
+              echo "Updating early adopters."
+              dest_file=${GITHUB_WORKSPACE}/deploy/src/settings_early.py
+              state_file=prod_early_adopter.sls
+              config_folder=logistics-core-early
+              var_name=PROD_EARLY_ADOPTER_SETTINGS
+              ;;
+            "release")
+              echo "Updating release."
+              dest_file=${GITHUB_WORKSPACE}/deploy/src/settings_release.py
+              state_file=prod_early_adopter.sls
+              config_folder=logistics-core-early
+              var_name=RELEASE_ADOPTER_SETTINGS
+              ;;
+            "prod")
+              echo "Updating prod."
+              dest_file=${GITHUB_WORKSPACE}/deploy/src/settings_prod.py
+              state_file=prod_release.sls
+              config_folder=logistics-core-prod
+              var_name=PROD_ADOPTER_SETTINGS
+              ;;
+            *)
+              echo "Invalid argument: $1"
+              exit 1
+              ;;
+          esac
+
+          cp ${GITHUB_WORKSPACE}/deploy/src/template.py $dest_file
+          sed -i 's/REPLACE_ME_GIT_TAG/${{ steps.extract_tag_name.outputs.tag_name }}/g' $dest_file
+          sed -i 's/REPLACE_ME_GIT_SHA/${{ steps.extract_sha.outputs.sha }}/g' $dest_file
+          sed -i 's/REPLACE_ME_CONFIG_FOLDER/$config_folder/g' $dest_file
+          sed -i 's/REPLACE_ME_SLS_FILENAME/$state_file/g' $dest_file
+          sed -i 's/REPLACE_ME_EXPORT_VAR/$var_name/g' $dest_file
+        }
+
     - name: Checkout repository
       uses: actions/checkout@v2
 
@@ -31,13 +71,14 @@ jobs:
 
     - name: Make changes in the deploy repository (early adopters)
       run: |
-        # Stage and commit changes for early adopters
-        cp ${GITHUB_WORKSPACE}/deploy/src/template.py ${GITHUB_WORKSPACE}/deploy/src/settings.py
-        sed -i 's/REPLACE_ME_GIT_TAG/${{ steps.extract_tag_name.outputs.tag_name }}/g' ${GITHUB_WORKSPACE}/deploy/src/settings.py
-        sed -i 's/REPLACE_ME_GIT_SHA/${{ steps.extract_sha.outputs.sha }}/g' ${GITHUB_WORKSPACE}/deploy/src/settings.py
-        sed -i 's/REPLACE_ME_CONFIG_FOLDER/logistics-core-early/g' ${GITHUB_WORKSPACE}/deploy/src/settings.py
-        sed -i 's/REPLACE_ME_SLS_FILENAME/prod_early_adopter.sls/g' ${GITHUB_WORKSPACE}/deploy/src/settings.py
-
+        update_release_settings "early"
+        # # Stage and commit changes for early adopters
+        # cp ${GITHUB_WORKSPACE}/deploy/src/template.py ${GITHUB_WORKSPACE}/deploy/src/settings.py
+        # sed -i 's/REPLACE_ME_GIT_TAG/${{ steps.extract_tag_name.outputs.tag_name }}/g' ${GITHUB_WORKSPACE}/deploy/src/settings.py
+        # sed -i 's/REPLACE_ME_GIT_SHA/${{ steps.extract_sha.outputs.sha }}/g' ${GITHUB_WORKSPACE}/deploy/src/settings.py
+        # sed -i 's/REPLACE_ME_CONFIG_FOLDER/logistics-core-early/g' ${GITHUB_WORKSPACE}/deploy/src/settings.py
+        # sed -i 's/REPLACE_ME_SLS_FILENAME/prod_early_adopter.sls/g' ${GITHUB_WORKSPACE}/deploy/src/settings.py
+        # sed -i 's/REPLACE_ME_EXPORT_VAR/PROD_EARLY_ADOPTER_SETTINGS/g' ${GITHUB_WORKSPACE}/deploy/src/settings.py
       shell: bash
 
     - name: Create and push branch and open pull request
@@ -50,52 +91,4 @@ jobs:
         title: 'Update Early adopters ${{ steps.extract_tag_name.outputs.tag_name }}'
         body: 'This is an automated pull request to update from the core repository. ${{ steps.extract_tag_name.outputs.tag_name }}'
         base: 'main' # Target branch in the deploy repository
-        branch: 'update-from-core-${{ github.sha }}'
-
-
-  update-prod:
-    runs-on: ubuntu-latest
-
-    steps:
-    - name: Checkout repository
-      uses: actions/checkout@v2
-
-    - name: Extract latest commit SHA
-      id: extract_sha
-      run: echo "::set-output name=sha::$(git rev-parse HEAD)"
-
-    - name: Extract release tag name
-      id: extract_tag_name
-      run: echo "::set-output name=tag_name::${{ github.event.release.tag_name }}"
-
-
-    - name: Checkout deploy repository
-      uses: actions/checkout@v3
-      with:
-        repository: 'ctmackay/deploy'
-        token: ${{ secrets.DEPLOY_REPO_TOKEN }}
-        ref: 'main' # Change to your default branch if it's not 'main'
-        path: 'deploy'
-
-    - name: Make changes in the deploy repository (prod)
-      run: |
-        # Stage and commit changes for early adopters settings_prod.py
-        cp ${GITHUB_WORKSPACE}/deploy/src/template.py ${GITHUB_WORKSPACE}/deploy/src/settings_prod.py
-        sed -i 's/REPLACE_ME_GIT_TAG/${{ steps.extract_tag_name.outputs.tag_name }}/g' ${GITHUB_WORKSPACE}/deploy/src/settings_prod.py
-        sed -i 's/REPLACE_ME_GIT_SHA/${{ steps.extract_sha.outputs.sha }}/g' ${GITHUB_WORKSPACE}/deploy/src/settings_prod.py
-        sed -i 's/REPLACE_ME_CONFIG_FOLDER/logistics-core-early/g' ${GITHUB_WORKSPACE}/deploy/src/settings_prod.py
-        sed -i 's/REPLACE_ME_SLS_FILENAME/prod_early_adopter.sls/g' ${GITHUB_WORKSPACE}/deploy/src/settings_prod.py
-
-      shell: bash
-
-    - name: Create and push branch and open pull request
-      uses: peter-evans/create-pull-request@v3
-      with:
-        token: ${{ secrets.DEPLOY_REPO_TOKEN }}
-        path: 'deploy'
-        delete-branch: true
-        commit-message: 'Prerelease update'
-        title: 'Update general population ${{ steps.extract_tag_name.outputs.tag_name }}'
-        body: 'This is an automated pull request to update from the core repository. ${{ steps.extract_tag_name.outputs.tag_name }}'
-        base: 'main' # Target branch in the deploy repository
-        branch: 'update-prod-from-core-${{ github.sha }}'
+        branch: 'update-early-adopters-${{ github.sha }}'
